apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card
        image: card:latest
